/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_UPDATE_PB_H_INCLUDED
#define PB_UPDATE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DeviceUpdateMsg { 
    pb_callback_t deviceId; 
    pb_callback_t sensor; 
} DeviceUpdateMsg;

typedef struct _SensorUpdateMsg { 
    pb_callback_t sensorId; 
    pb_size_t which_value;
    union {
        int32_t valueInt;
        float valueFloat;
        bool valueBool;
    } value; 
} SensorUpdateMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DeviceUpdateMsg_init_default             {{{NULL}, NULL}, {{NULL}, NULL}}
#define SensorUpdateMsg_init_default             {{{NULL}, NULL}, 0, {0}}
#define DeviceUpdateMsg_init_zero                {{{NULL}, NULL}, {{NULL}, NULL}}
#define SensorUpdateMsg_init_zero                {{{NULL}, NULL}, 0, {0}}

/* Field tags (for use in manual encoding/decoding) */
#define DeviceUpdateMsg_deviceId_tag             1
#define DeviceUpdateMsg_sensor_tag               2
#define SensorUpdateMsg_sensorId_tag             1
#define SensorUpdateMsg_valueInt_tag             2
#define SensorUpdateMsg_valueFloat_tag           3
#define SensorUpdateMsg_valueBool_tag            4

/* Struct field encoding specification for nanopb */
#define DeviceUpdateMsg_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   deviceId,          1) \
X(a, CALLBACK, REPEATED, MESSAGE,  sensor,            2)
#define DeviceUpdateMsg_CALLBACK pb_default_field_callback
#define DeviceUpdateMsg_DEFAULT NULL
#define DeviceUpdateMsg_sensor_MSGTYPE SensorUpdateMsg

#define SensorUpdateMsg_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   sensorId,          1) \
X(a, STATIC,   ONEOF,    INT32,    (value,valueInt,value.valueInt),   2) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,valueFloat,value.valueFloat),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (value,valueBool,value.valueBool),   4)
#define SensorUpdateMsg_CALLBACK pb_default_field_callback
#define SensorUpdateMsg_DEFAULT NULL

extern const pb_msgdesc_t DeviceUpdateMsg_msg;
extern const pb_msgdesc_t SensorUpdateMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DeviceUpdateMsg_fields &DeviceUpdateMsg_msg
#define SensorUpdateMsg_fields &SensorUpdateMsg_msg

/* Maximum encoded size of messages (where known) */
/* DeviceUpdateMsg_size depends on runtime parameters */
/* SensorUpdateMsg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
